In [33]:
#Q1 Combining a 1D and 2D NumPy Array
import numpy as np

arr1 = np.array([1,2,3])

arr2 = np.array([
    [4,5,6],
    [7,8,9]
])

res = np.vstack((arr1, arr2))

print(res)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:
#Q2 Flatten a 2D Array into 1D
import numpy as np

arr = np.array([
    [1,2,3],
    [4,5,6]
])

print(arr.flatten())

[1 2 3 4 5 6]


In [35]:
#Q3 Reverse a NumPy Array
import numpy as np

arr = np.array([10,20,30,40,50])

print(arr[::-1])

[50 40 30 20 10]


In [36]:
#Q4 Practice Operations
import numpy as np

arr = np.array([
    [10,20,30],
    [40,50,60]
])
print(arr)

print("Maximum:", np.max(arr))

print("Minimum:", np.min(arr))

print("sum:", np.sum(arr))

print("Rows:", arr.shape[0])

print("Columns:", arr.shape[1])

print("Specific Element:", arr[0,2])

sum1 = 0

for row in arr:
    for item in row:
        sum1 += item

print(sum1)



[[10 20 30]
 [40 50 60]]
Maximum: 60
Minimum: 10
sum: 210
Rows: 2
Columns: 3
Specific Element: 30
210


In [37]:
a = np.array([10,20,30])
b = np.array([1,2,3])

print(a+b)
print(a-b)
print(a*b)
print(a/b)

[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]


In [38]:
#Q5 Iterate 3D Array using for loop and nditer
import numpy as np

arr = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

print("Using For Loop")

for x in arr:
    for y in x:
        for z in y:
            print(z)



for x in np.nditer(arr):
    print(x)

Using For Loop
1
2
3
4
5
6
7
8
1
2
3
4
5
6
7
8


In [39]:
#Q6 Average, Mean, Median, Mode of Two 2D Arrays
import numpy as np
from statistics import mode

arr1 = np.array([
    [1,2,3,4,5],
    [3,4,2,7,8]
])

arr2 = np.array([
    [5,6,2,9,4],
    [7,8,2,4,7]
])

avg = (arr1 + arr2)/2

print("Average Array")
print(avg)

combined = np.concatenate((arr1.flatten(),
                           arr2.flatten()))

print("Mean:", np.mean(combined))
print("Median:", np.median(combined))
print("Mode:", mode(combined))

Average Array
[[3.  4.  2.5 6.5 4.5]
 [5.  6.  2.  5.5 7.5]]
Mean: 4.65
Median: 4.0
Mode: 2
