In [ ]:
#Q1 Replace NaN with 0 and interchange rows/columns
import numpy as np

arr = np.array([
    [6, -8, 73, -110],
    [np.nan, -8, 0, 94]
])

# Replace NaN with 0
arr = np.nan_to_num(arr, nan=0)

print("After Replacing NaN:")
print(arr)

# Interchange rows and columns
res = arr.T

print("\nTranspose Matrix:")
print(res)

After Replacing NaN:
[[   6.   -8.   73. -110.]
 [   0.   -8.    0.   94.]]

Transpose Matrix:
[[   6.    0.]
 [  -8.   -8.]
 [  73.    0.]
 [-110.   94.]]


In [ ]:
#Q2 Move axes of 3D array
import numpy as np

arr = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])


print(arr)

res = np.moveaxis(arr, 0, -1)


print(res)

Original Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

After Moving Axis:
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [4]:
#Q3 Replace NaN with column average
import numpy as np

arr = np.array([
    [1,2,np.nan],
    [4,np.nan,6],
    [7,8,9]
])

# Column mean
mean = np.nanmean(arr, axis=0)


index = np.where(np.isnan(arr))

# Replace NaN
arr[index] = np.take(mean, index[1])

print(arr)

[[1.  2.  7.5]
 [4.  5.  6. ]
 [7.  8.  9. ]]


In [3]:
#Q4 Replace negative values with zero
import numpy as np

arr = np.array([2,-5,7,-9,4])

arr[arr < 0] = 0

print(arr)

[2 0 7 0 4]
